import React from 'react'
import './globals.css'
import { ThemeProvider } from './src/utils/ThemeContext'

export const metadata = {
  title: 'My Portfolio',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <ThemeProvider>
      <html lang="en">
        <body>{children}</body>
      </html>
    </ThemeProvider>
  )
}
