import React from 'react'
import './globals.css'
import { ThemeProvider } from './src/utils/ThemeContext'
import Head from 'next/head'


export const metadata = {
  title: 'My Portfolio',
  description: 'Generated by create next app',
}


export default function RootLayout({ children }) {
  return (
    <ThemeProvider>
      <Head>
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/* Other meta tags can go here */}
      </Head>
      <html lang="en">
        <body>{children}</body>
      </html>
    </ThemeProvider>
  );
}